version: "3.7"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: general
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    # volumes:
    # - ./schemas/mysql/dml:dml
