name: CloudFormation S3 Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: upload cfn file to s3
        env:
          S3_CFN_BUCKET_NAME: ${{ secrets.S3_CFN_BUCKET_NAME }}
        run: |
          aws s3 sync ./infra/cloudformation s3://${S3_CFN_BUCKET_NAME}
