name: deploy infra

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      component:
        description: cloudformation template
        default: network
        type: choice
        options:
          - network

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: deploy
        env:
          STACK_NAME: sandbox-network
          TEMPLATE_FILE: ./infra/cloudformation/${{ github.event.inputs.component }}.json
        run: |
          aws cloudformation deploy \
          --stack-name ${STACK_NAME} \
          --template-file ${TEMPLATE_FILE} \
          --no-fail-on-empty-changeset
