name: update infra TODO

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      component:
        description: cloudformation template
        default: network
        type: choice
        options:
          - network

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: upload cfn to s3
        env:
          S3_CFN_BUCKET_NAME: ${{ secrets.S3_CFN_BUCKET_NAME }}
        run: |
          aws s3 sync ./infra/cloudformation s3://${S3_CFN_BUCKET_NAME}

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: update
        env:
          STACK_NAME: sandbox-network
          BUCKET_NAME: ${{ secrets.S3_CFN_BUCKET_NAME }}
          TEMPLATE_FILE: ${{ github.event.inputs.component }}.json
        run: |
          aws cloudformation update-stack \
          --stack-name ${STACK_NAME} \
          --no-use-previous-template \
          --template-url "https://${BUCKET_NAME}.s3.ap-northeast-1.amazonaws.com/${TEMPLATE_FILE}"
