name: wf-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: output job url
        env:
          WORKFLOW_URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/run/$GITHUB_RUN_ID/job/$GITHUB_RUN_NUMBER
        run: |
          echo WORKFLOW_URL=${{ env.WORKFLOW_URL }}
          echo 'WORKFLOW_URL="${{ env.WORKFLOW_URL }}"'
